services:
  football-fan-api:
    container_name: football-fan-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    environment:
      - PY_ENV=production
      - POSTGRES__HOST=192.168.1.100
      - REDIS__HOST=192.168.1.100
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/up"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  
