services:
  # Default service - shows help
  football-fan-ai:
    build: .
    container_name: football-fan-ai-agent
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./db:/app/db
    working_dir: /app
    command: ["python", "main.py", "--help"]
    profiles:
      - default

  # Service for loading database
  load-database:
    build: .
    container_name: football-fan-ai-load-db
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./db:/app/db
    working_dir: /app
    command: ["python", "main.py", "load-database"]
    profiles:
      - commands

  # Service for adding team to calendar
  add-to-calendar:
    build: .
    container_name: football-fan-ai-calendar
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./db:/app/db
    working_dir: /app
    command: ["python", "main.py", "add-to-calendar", "TEAM_NAME"]
    profiles:
      - commands

  # Service for interactive shell
  shell:
    build: .
    container_name: football-fan-ai-shell
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./db:/app/db
      - ./src:/app/src
    working_dir: /app
    command: ["/bin/bash"]
    stdin_open: true
    tty: true
    profiles:
      - commands

  # Service for running hello command
  hello:
    build: .
    container_name: football-fan-ai-hello
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./db:/app/db
    working_dir: /app
    command: ["python", "main.py", "hello", "World"]
    profiles:
      - commands

  # Service for running the scheduler
  scheduler:
    build: .
    container_name: football-fan-ai-scheduler
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./db:/app/db
      - ./src:/app/src
    working_dir: /app
    command: ["python", "scheduler.py"]
    restart: unless-stopped
    profiles:
      - commands
      - scheduler

  # Service for Google Calendar operations
  calendar-list:
    build: .
    container_name: football-fan-ai-calendar-list
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./db:/app/db
      - ./credentials.json:/app/credentials.json:ro
      - ./token.json:/app/token.json
    working_dir: /app
    command: ["python", "main.py", "calendar-list"]
    profiles:
      - commands
      - calendar

  # Service for adding team to Google Calendar
  add-team-to-calendar:
    build: .
    container_name: football-fan-ai-add-team-calendar
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./db:/app/db
      - ./credentials.json:/app/credentials.json:ro
      - ./token.json:/app/token.json
    working_dir: /app
    command: ["python", "main.py", "add-team-to-calendar", "TEAM_NAME"]
    profiles:
      - commands
      - calendar

  # Service for Google Calendar setup guide
  setup-calendar:
    build: .
    container_name: football-fan-ai-setup-calendar
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./db:/app/db
    working_dir: /app
    command: ["python", "main.py", "setup-calendar"]
    profiles:
      - commands
      - calendar
