from enum import Enum


class Team(str, Enum):
    FLAMENGO = "FLAMENGO"
    PALMEIRAS = "PALMEIRAS"
    CRUZEIRO = "CRUZEIRO"
    MIRASSOL = "MIRASSOL"
    BAHIA = "BAHIA"
    BOTAFOGO = "BOTAFOGO"
    SAO_PAULO = "SAO_PAULO"
    BRAGANTINO = "BRAGANTINO"
    CORINTHIANS = "CORINTHIANS"
    FLUMINENSE = "FLUMINENSE"
    INTERNACIONAL = "INTERNACIONAL"
    CEARA = "CEARA"
    GREMIO = "GREMIO"
    ATLETICO_MG = "ATLETICO_MG"
    VASCO = "VASCO"
    SANTOS = "SANTOS"
    VITORIA = "VITORIA"
    JUVENTUDE = "JUVENTUDE"
    FORTALEZA = "FORTALEZA"
    SPORT = "SPORT"
